.\.venv\Scripts\Activate.ps1
cd ui
$env:VITE_ENGINE_PROVIDER="adapter"
$env:EARLOOP_PYTHON_EXECUTABLE="python"
$env:EARLOOP_PYCHARM_DEBUG="1"
$env:EARLOOP_PYCHARM_DEBUG_HOST="127.0.0.1"
$env:EARLOOP_PYCHARM_DEBUG_PORT="5678"
$env:EARLOOP_PYCHARM_DEBUG_SUSPEND="1"
npm run dev