import type { OnboardingStep } from "@/features/onboarding/types";

export const APP_ONBOARDING_VERSION = 1;

export const appOnboardingSteps: OnboardingStep[] = [
  {
    id: "intro",
    screen: "settings",
    type: "info",
    presentation: "intro",
    title: "Познакомимся с основным сценарием EarLoop",
    description: "Сейчас приложение коротко покажет, как выбрать аудиоустройства, начать новую сессию, сравнивать варианты и сохранить результат.",
    nextLabel: "Начать",
    canGoBack: false,
  },
  {
    id: "audio-devices",
    screen: "settings",
    type: "action",
    title: "Выбор аудиоустройств",
    description: "Сначала в Windows переключи вывод на CABLE Input. Затем выбери источник захвата для EarLoop. Если появится ошибка, проверь в настройках звука Windows, что у CABLE Output и устройства вывода совпадает sample rate.",
    targetId: "audio-setup-card",
    placement: "right",
    nextLabel: "Следующий шаг",
  },
  {
    id: "home-new-profile",
    screen: "home",
    type: "action",
    title: "Главный экран",
    description: "Создание нового профиля начинается из раздела «Новый профиль». Нажми на него в боковой панели.",
    targetId: "sidebar-new-profile",
    placement: "right",
    completeOn: ["navigation.new-profile.clicked"],
    screenAfterCompleted: "session",
    autoAdvanceOnComplete: true,
    nextLabel: "Следующий шаг",
  },
  {
    id: "session-base-profile",
    screen: "session",
    type: "action",
    title: "Базовый профиль",
    description: "Здесь можно стартовать с нуля или взять существующий профиль за основу. Открой список, выбери значение или просто закрой его, если всё уже подходит.",
    targetId: "session-base-profile",
    placement: "bottom",
    completeOn: ["session.base-profile.interacted", "onboarding.step4.dismissed"],
    nextLabel: "Следующий шаг",
  },
  {
    id: "session-start",
    screen: "session",
    type: "action",
    title: "Запуск сессии",
    description: "После нажатия «Начать» появится первая пара для сравнения.",
    targetId: "session-start-button",
    placement: "top",
    completeOn: ["session.start.clicked"],
    nextLabel: "Следующий шаг",
  },
  {
    id: "compare-ab",
    screen: "session",
    type: "action",
    title: "Сравнение A/B",
    description: "Переключай карточки A и B, чтобы слушать оба варианта и сравнить разницу.",
    targetId: "compare-cards",
    placement: "bottom",
    completeOn: ["session.compare.card.clicked"],
    nextLabel: "Следующий шаг",
  },
  {
    id: "compare-previous-choice",
    screen: "session",
    type: "info",
    title: "Прошлый выбор",
    description: "Если новые варианты не подошли, кнопка «Слушать прошлый выбор» возвращает тебя к предыдущей базе.",
    targetId: "compare-toolbar",
    placement: "top",
    autoScroll: "smooth-end",
    nextLabel: "Понял",
  },
  {
    id: "compare-feedback",
    screen: "session",
    type: "action",
    title: "Обратная связь",
    description: "Здесь можно указать, чего не хватает в звучании, и затем сгенерировать следующую пару.",
    targetId: "feedback-panel",
    placement: "top",
    autoScroll: "smooth-start",
    completeOn: ["session.generate-next.clicked"],
    nextLabel: "Следующий шаг",
  },
  {
    id: "compare-finish",
    screen: "session",
    type: "action",
    title: "Завершение",
    description: "Когда подбор устраивает, нажми «Завершить», чтобы перейти к экрану сохранения результата.",
    targetId: "finish-button",
    placement: "top",
    completeOn: ["session.finish.clicked"],
    nextLabel: "Следующий шаг",
  },
  {
    id: "result-screen",
    screen: "session",
    type: "info",
    title: "Сохранение профиля",
    description: "Здесь можно дать профилю имя, сохранить результат или вернуться назад и продолжить подбор. Сохранять прямо сейчас не обязательно.",
    targetId: "result-actions",
    placement: "bottom",
    nextLabel: "Завершить обучение",
  },
];
